a = input(' digite Algo: ')
print('O tipo primitivo do que vc digitou é:', type(a))
print('Só tem espaço? ',a.isspace())
print('Só tem Maiusculas? ',a.isupper())
print('é um numero? ',a.isnumeric())
print('está capitalizada? ',a.istitle())
