print('qual seu nome?')
myName = input()
print("muito prazer", myName)
print("seu nome tem: ",(len(myName))," Letras")
print("Qual sua idade?")
myAge = input()
myAge = float(myAge)
myAge = int(myAge)
print("vc tem",myAge," anos")
print("e vc terá",myAge+1, "anos no ano que vem")
print("entre com um numero")
num = input()
num = float(num)
num = int(num)
num2 = num
print("o numero digitado foi:",num)
print("a multiplicação de",num,"por ele mesmo é:",num*num2)
